'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SoftwareDevelopmentChat.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to jBZMdmeUTsSZ5B+vUgAiLXn0zmRFJnSXRmWXve+vUVYuBBAdek1T3dBJASggsyfiUWLDIlwnhUPgueAWdKuQD1eLecSsayMJNvUZhzCLVeINoI9LzJhdGfVXkHaCuK6jowd5/hlgs516dd91Pb9KNqNH3TGd9B8ufdhFmX8MySGwDp6zx7IR+7Zi1iY6FxdF56r5OQcZlkpnaxdoV8kKfxce+vj3JQI87o4GjBuNIiwpWoykfCm5apif4QN3t1CPPagU/uWbZAvS6UQjXguUHJLJnF2lZCdmas2PCC+DdxulJoGt6Yw/VACickPdkJ7I9MGPdcymbvYQzyw7I2SX4sIEy2IZapy4//fYuS9945Z7fAH3LN8TDCdAqfBJyHiuFsyMCMFI/+Qjkrqdbyk2rF3CWsdQiZrztqB7fR7rjAGR7TGW2MZfx7beEHb26V+3kUk0Pv5d41kNNgji7rsfhLpw39sUIPv84261azT29C7yWgoXuwvvZS083nOY3wfT [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property swears() As String
            Get
                Return ResourceManager.GetString("swears", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
